/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Controladores.PacienteC;
import Controladores.HistorialC;
import Controladores.Conexion;
import Modelos.Paciente;
import Modelos.Historial;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asali
 */
public class HistorialReporte extends javax.swing.JFrame {

    /**
     * Creates new form HistorialReporte
     */
    private Paciente paciente;
    public Conexion conexion;
    public Connection link;
    
    public HistorialReporte(Paciente paciente) {
        this.paciente = paciente;
        initComponents();
        conexion=new Conexion();
        link=conexion.Conectar();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Ttable = new javax.swing.JTable();
        btnDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ttable.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Ttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Apellido", "Nacimiento", "Direccion", "Telefono", "Correo", "Altura", "Peso", "GrupSanguineo", "Alergias", "Genero", "Pre-Existencias", "Dia", "Receta", "Observaciones", "Examenes"
            }
        ));
        jScrollPane1.setViewportView(Ttable);
        Ttable.getAccessibleContext().setAccessibleName("");

        btnDatos.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnDatos.setText("Cargar");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(883, Short.MAX_VALUE)
                .addComponent(btnDatos)
                .addGap(665, 665, 665))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDatos)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed

        
        ArrayList<Historial>ListaH= new ArrayList<Historial>();
        HistorialC historial = new HistorialC();
        ListaH = historial.Leer(link);
        
        
        for(int i=0;i<ListaH.size();i++){
            
            if (ListaH.get(i).getFicha().equals(paciente.getRut()))
 
            {
                Object[] row = {paciente.getRut(),paciente.getNombre(),paciente.getApellido(),paciente.getFecha_nacimiento(),paciente.getDireccion(),paciente.getTelefono(),paciente.getCorreo(),paciente.getAltura(),paciente.getPeso(),paciente.getGrupo_sanguineo(),paciente.getAlergias(),paciente.getGenero(),paciente.getPre_existencias(),ListaH.get(i).getDia_consulta(),ListaH.get(i).getReceta_Entregada(),ListaH.get(i).getObs(),ListaH.get(i).getExamenes()};
                DefaultTableModel model = (DefaultTableModel) Ttable.getModel();
                model.insertRow(i, row);
            }
        }

    }//GEN-LAST:event_btnDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Paciente pacienteEjemplo = new Paciente();

                new HistorialReporte(pacienteEjemplo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ttable;
    private javax.swing.JButton btnDatos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
